apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cern-auth-proxy
    app.kubernetes.io/name: cern-auth-proxy
    app.kubernetes.io/part-of: cern-auth-proxy
    app.kubernetes.io/version: latest
  name: cern-auth-proxy
  namespace: cmsrunregistry
spec:
  type: ClusterIP
  ports:
    - name: sso-proxy
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app.kubernetes.io/instance: cern-auth-proxy
    app.kubernetes.io/name: cern-auth-proxy
